# Japan Population Analysis

In this project, I analyze population data of Japan across different prefectures.

The goal is to understand how population is distributed and apply statistical concepts such as mean, median, and measures of spread on real-world data.

This project builds on basic statistical concepts and applies them to a real dataset.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

## Loading the Dataset

The dataset is loaded using pandas. It contains population data categorized by prefecture, age group, gender, and year.

In [2]:
df = pd.read_csv("data/japanese_census.csv")
df.head()

,Unnamed: 0,Year,Prefecture,Age Lower Bound,Age Upper Bound,Gender,Population
0,0,1920,Hokkaido,0,4.0,Male,190044
1,1,1920,Hokkaido,0,4.0,Female,186632
2,2,1920,Hokkaido,5,9.0,Male,161814
3,3,1920,Hokkaido,5,9.0,Female,157556
4,4,1920,Hokkaido,10,14.0,Male,138018

## Understanding the Dataset

Before analysis, it is important to understand the structure of the data, including available columns.

In [3]:
df.columns

Index(['Unnamed: 0', 'Year', 'Prefecture', 'Age Lower Bound',
       'Age Upper Bound', 'Gender', 'Population'],
      dtype='str')

##  Data Cleaning

The dataset contains unnecessary columns and multiple breakdowns such as age, gender, year. 

To make the data usable:
- Remove unnecessary columns  
- Filter data for the latest year  
- Aggregate population for each prefecture

In [8]:
df = df.drop(columns=['Unnamed: 0'], errors='ignore') #since the column would be deleted and if the code ran again it will give error
df = df[df['Year'] == df['Year'].max()]
df['Prefecture'] = df['Prefecture'].replace('Tokyo Metropolis', 'Tokyo Prefecture') # as tokyo prefecture is commonly named tokyo metropolis or tokyo-to
df_grouped = df.groupby('Prefecture')['Population'].sum().reset_index()
df_grouped.head()

          Prefecture  Population
0   Aichi Prefecture     7401952
1   Akita Prefecture     1014579
2  Aomori Prefecture     1297015
3   Chiba Prefecture     6126343
4   Ehime Prefecture     1362407

### Note on Dataset

The dataset contains 46 administrative regions instead of the expected 47 prefectures of Japan.

This may be due to how the dataset categorizes regions. The analysis will proceed using the available data.